/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

/**
 *
 * @author asus
 */
public class Datauser extends javax.swing.JFrame {

    /**
     * Creates new form Datauser
     */
    public Datauser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        name = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        idk = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        idk1 = new javax.swing.JLabel();
        address1 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabeldata.setBackground(new java.awt.Color(153, 153, 153));
        tabeldata.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        tabeldata.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID User", "Nama user", "Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabeldata.setGridColor(new java.awt.Color(0, 0, 0));
        tabeldata.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        name.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        address.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        address.setText("Password");

        idk.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        idk.setText("ID User");

        Delete.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Kembali.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        username.setText("Username :");

        Reset.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Insert.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        Insert.setText("Insert");
        Insert.setBorder(null);
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        idk1.setFont(new java.awt.Font("DFPOP1-W9", 1, 36)); // NOI18N
        idk1.setForeground(new java.awt.Color(0, 102, 102));
        idk1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idk1.setText("Data User di Hotel ReG");

        address1.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        address1.setText("Level");

        level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Client", "Admin", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(idk1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password)
                                .addComponent(level, 0, 218, Short.MAX_VALUE))
                            .addGap(145, 145, 145))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(291, 291, 291)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(idk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(565, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idk1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(idk, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(514, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:

        int input  = tabeldata.getSelectedRow();
        DefaultTableModel tm = (DefaultTableModel) tabeldata.getModel();
        id.setText(tm.getValueAt(input,0).toString());
        name.setText(tm.getValueAt(input,1).toString());
        password.setText(tm.getValueAt(input,2).toString());
        birthdate.setDateFormatString(tm.getValueAt(input,3).toString());
        hp.setText(tm.getValueAt(input,4).toString());
        kelamin.setSelectedItem(tm.getValueAt(input,5).toString());
        checkin.setDateFormatString(tm.getValueAt(input,6).toString());
        checkout.setDateFormatString(tm.getValueAt(input,7).toString());
        type.setSelectedItem(tm.getValueAt(input,8).toString());
        nokamar.setSelectedItem(tm.getValueAt(input,9).toString());
        harga.setText(tm.getValueAt(input,10).toString());
    }//GEN-LAST:event_tabeldataMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        //Membuat format tanggal di Java sama dengan Mysql
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        try{
            //Menghubungkan antara client server dan database
            Interfacehotel dbi=(Interfacehotel)Naming.lookup("rmi://localhost:2021/costumer");
            //Menyimpan hasil data dari Client ke tiap-tiap entitas
            int upid =Integer.parseInt(id.getText());
            String result=dbi.Delete(upid);
            //Menampilkan error atau suksesnya saaat mendelete data
            JOptionPane.showMessageDialog(null, result,"Sukses",JOptionPane.INFORMATION_MESSAGE);
            //Menghapus inputan
            clearInput();
        } catch (NumberFormatException | NotBoundException | MalformedURLException | RemoteException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex,"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

    }//GEN-LAST:event_DeleteActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        frame =new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Apakah kamu ingin menutup ? ","Manejemen Hotel ReG",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_KembaliActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed

        clearInput();
    }//GEN-LAST:event_ResetActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        //Membuat format tanggal di Java sama dengan Mysql
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        try{
            //Menghubungkan antara client server dan database
            Interfacehotel dbi=(Interfacehotel)Naming.lookup("rmi://localhost:2021/costumer");
            //Menyimpan hasil data dari Client ke tiap-tiap entitas
            int htid =Integer.parseInt(id.getText());
            String htusername = name.getText();
            String htaddress = password.getText();
            String htbirthdate = String.valueOf(fm.format(birthdate.getDate()));
            String htnohp=hp.getText();
            String htkelamin=kelamin.getSelectedItem().toString();
            String htcekin = String.valueOf(fm.format(checkin.getDate()));
            String htcekout = String.valueOf(fm.format(checkout.getDate()));
            String httykamar=type.getSelectedItem().toString();
            String htkamar=nokamar.getSelectedItem().toString();
            String htprice=harga.getText();

            String result = dbi.Insert(htid, htusername, htaddress, htbirthdate, htnohp, htkelamin, htcekin, htcekout, httykamar, htkamar, htprice);
            DefaultTableModel defTable = (DefaultTableModel) tabeldata.getModel();
            defTable.setRowCount(0);
            //Menampilkan data hasil inputan
            tampilancostumer();
            //Menghapus inputan
            clearInput();
            //Menampilkan feedback dari server
            JOptionPane.showMessageDialog(null, result,"Sukses",JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException | NotBoundException | MalformedURLException | RemoteException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex,"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_InsertActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        //Membuat format tanggal di Java sama dengan Mysql
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        try{
            //Menghubungkan antara client server dan database
            Interfacehotel dbi=(Interfacehotel)Naming.lookup("rmi://localhost:2021/costumer");
            //Menyimpan hasil data dari Client ke tiap-tiap entitas
            int upid =Integer.parseInt(id.getText());
            String upusername = name.getText();
            String upaddress = password.getText();
            //String upbirthdate = birthdate.setDateFormatString();
            String upbirthdate = String.valueOf(fm.format(birthdate.getDate()));
            String upnohp=hp.getText();
            String upkelamin=kelamin.getSelectedItem().toString();
            String upcekin = String.valueOf(fm.format(checkin.getDate()));
            String upcekout = String.valueOf(fm.format(checkout.getDate()));
            String uptykamar=type.getSelectedItem().toString();
            String upkamar=nokamar.getSelectedItem().toString();
            String upprice=harga.getText();

            String result = dbi.Update(upid, upusername, upaddress, upbirthdate, upnohp, upkelamin, upcekin, upcekout, uptykamar, upkamar, upprice);
            DefaultTableModel defTable = (DefaultTableModel) tabeldata.getModel();
            defTable.setRowCount(0);
            //Menampilkan data hasil inputan
            tampilancostumer();
            //Menampilkan feedback dari server
            JOptionPane.showMessageDialog(null, result,"Sukses",JOptionPane.INFORMATION_MESSAGE);
            //Menghapus inputan
            clearInput();
            //Menampilkan error saaat mengupdate data
        } catch (NumberFormatException | NotBoundException | MalformedURLException | RemoteException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex,"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datauser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Delete;
    public javax.swing.JButton Insert;
    public javax.swing.JButton Kembali;
    public javax.swing.JButton Reset;
    public javax.swing.JLabel address;
    public javax.swing.JLabel address1;
    public javax.swing.JTextField id;
    public javax.swing.JLabel idk;
    public javax.swing.JLabel idk1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox level;
    public javax.swing.JTextField name;
    public javax.swing.JTextField password;
    public javax.swing.JTable tabeldata;
    public javax.swing.JButton update;
    public javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
