/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Datacostumer extends javax.swing.JFrame {

    /**
     * Creates new form Datacostumer
     */
    public Datacostumer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        cekin = new javax.swing.JLabel();
        jkelamin = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        nohp = new javax.swing.JLabel();
        tlahir = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        idk = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        txt_tykamar = new javax.swing.JComboBox();
        txt_alamat = new javax.swing.JTextField();
        txt_kelamin = new javax.swing.JComboBox();
        txt_nokamar = new javax.swing.JComboBox();
        typekamar = new javax.swing.JLabel();
        kamar = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_hp = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        idk1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        cekout = new javax.swing.JLabel();
        txt_checkout = new com.toedter.calendar.JDateChooser();
        txt_birthdate = new com.toedter.calendar.JDateChooser();
        txt_checkin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabeldata.setBackground(new java.awt.Color(153, 153, 153));
        tabeldata.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        tabeldata.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "username", "alamat", "tanggal lahir", "No.Hp", "Jenis Kelamin", "Tanggal Checkin", "Tanggal Checkout", "Type kamar", "No. Kamar", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabeldata.setGridColor(new java.awt.Color(0, 0, 0));
        tabeldata.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        cekin.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        cekin.setText("Check In :");

        jkelamin.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        jkelamin.setText("Jenis Kelamin :");

        txt_name.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        nohp.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        nohp.setText("No. HP :");

        tlahir.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        tlahir.setText("Tanggal Lahir :");

        address.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        address.setText("Alamat :");

        idk.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        idk.setText("ID");

        txt_harga.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Kembali.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        username.setText("Username :");

        Reset.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Insert.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        Insert.setText("Insert");
        Insert.setBorder(null);
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        price.setFont(new java.awt.Font("News706 BT", 0, 10)); // NOI18N
        price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price.setText("Rp");

        txt_tykamar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_tykamar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Type Kamar", "Single", "Double", "Family" }));
        txt_tykamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tykamarActionPerformed(evt);
            }
        });

        txt_alamat.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_kelamin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_kelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Jenis Kelamin", "Perempuan", "Laki-laki" }));
        txt_kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kelaminActionPerformed(evt);
            }
        });

        txt_nokamar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_nokamar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih No. Kamar", "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012", "013", "014", "015", "016", "017", "018", "019", "020", "021", "022", "023", "024", "025", "026", "027", "028", "029", "030", "031", "032", "033", "034", "035", "036", "037", "038", "039", "040", "041", "042", "043", "044", "045", "046", "047", "048", "049", "050" }));
        txt_nokamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nokamarActionPerformed(evt);
            }
        });

        typekamar.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        typekamar.setText("Type Kamar :");

        kamar.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        kamar.setText("No. Kamar :");

        txt_id.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_hp.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txt_hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hpActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        idk1.setFont(new java.awt.Font("DFPOP1-W9", 1, 36)); // NOI18N
        idk1.setForeground(new java.awt.Color(0, 102, 102));
        idk1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idk1.setText("Data Costumer di Hotel ReG");

        price1.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        price1.setText("Harga :");

        cekout.setFont(new java.awt.Font("News706 BT", 0, 12)); // NOI18N
        cekout.setText("Check Out :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(txt_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cekin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cekout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_hp)
                    .addComponent(txt_kelamin, 0, 161, Short.MAX_VALUE)
                    .addComponent(txt_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typekamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_tykamar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_harga)
                        .addComponent(txt_nokamar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(txt_name)
                                .addComponent(txt_alamat)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(322, 322, 322)
                            .addComponent(idk1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(246, 246, 246)
                            .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jkelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(cekin))
                                .addComponent(txt_checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typekamar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nokamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_tykamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cekout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(510, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(idk1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(idk, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4))
                                .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:

        int input  = tabeldata.getSelectedRow();
        DefaultTableModel tm = (DefaultTableModel) tabeldata.getModel();
        txt_id.setText(tm.getValueAt(input,0).toString());
        txt_name.setText(tm.getValueAt(input,1).toString());
        txt_alamat.setText(tm.getValueAt(input,2).toString());
        birthdate.setDateFormatString(tm.getValueAt(input,3).toString());
        txt_hp.setText(tm.getValueAt(input,4).toString());
        txt_kelamin.setSelectedItem(tm.getValueAt(input,5).toString());
        checkin.setDateFormatString(tm.getValueAt(input,6).toString());
        checkout.setDateFormatString(tm.getValueAt(input,7).toString());
        txt_tykamar.setSelectedItem(tm.getValueAt(input,8).toString());
        txt_nokamar.setSelectedItem(tm.getValueAt(input,9).toString());
        txt_harga.setText(tm.getValueAt(input,10).toString());
    }//GEN-LAST:event_tabeldataMouseClicked

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        //Membuat format tanggal di Java sama dengan Mysql
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        try{
            //Menghubungkan antara client server dan database
            Interfacehotel dbi=(Interfacehotel)Naming.lookup("rmi://localhost:2021/costumer");
            //Menyimpan hasil data dari Client ke tiap-tiap entitas
            int upid =Integer.parseInt(txt_id.getText());
            String result=dbi.Delete(upid);
            //Menampilkan error atau suksesnya saaat mendelete data
            JOptionPane.showMessageDialog(null, result,"Sukses",JOptionPane.INFORMATION_MESSAGE);
            //Menghapus inputan
            clearInput();
        } catch (NumberFormatException | NotBoundException | MalformedURLException | RemoteException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex,"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

    }//GEN-LAST:event_DeleteActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        frame =new JFrame("Kembali");
        if (JOptionPane.showConfirmDialog(frame, "Apakah kamu ingin menutup ? ","Manejemen Hotel ReG",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_KembaliActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed

        clearInput();
    }//GEN-LAST:event_ResetActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        //Membuat format tanggal di Java sama dengan Mysql
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        try{
            //Menghubungkan antara client server dan database
            Interfacehotel dbi=(Interfacehotel)Naming.lookup("rmi://localhost:2021/costumer");
            //Menyimpan hasil data dari Client ke tiap-tiap entitas
            int htid =Integer.parseInt(txt_id.getText());
            String htusername = txt_name.getText();
            String htaddress = txt_alamat.getText();
            String htbirthdate = String.valueOf(fm.format(birthdate.getDate()));
            String htnohp=txt_hp.getText();
            String htkelamin=txt_kelamin.getSelectedItem().toString();
            String htcekin = String.valueOf(fm.format(checkin.getDate()));
            String htcekout = String.valueOf(fm.format(checkout.getDate()));
            String httykamar=txt_tykamar.getSelectedItem().toString();
            String htkamar=txt_nokamar.getSelectedItem().toString();
            String htprice=txt_harga.getText();

            String result = dbi.Insert(htid, htusername, htaddress, htbirthdate, htnohp, htkelamin, htcekin, htcekout, httykamar, htkamar, htprice);
            DefaultTableModel defTable = (DefaultTableModel) tabeldata.getModel();
            defTable.setRowCount(0);
            //Menampilkan data hasil inputan
            tampilancostumer();
            //Menghapus inputan
            clearInput();
            //Menampilkan feedback dari server
            JOptionPane.showMessageDialog(null, result,"Sukses",JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException | NotBoundException | MalformedURLException | RemoteException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex,"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_InsertActionPerformed

    private void txt_tykamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tykamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tykamarActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kelaminActionPerformed

    private void txt_nokamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nokamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nokamarActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hpActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        //Membuat format tanggal di Java sama dengan Mysql
        String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        try{
            //Menghubungkan antara client server dan database
            Interfacehotel dbi=(Interfacehotel)Naming.lookup("rmi://localhost:2021/costumer");
            //Menyimpan hasil data dari Client ke tiap-tiap entitas
            int upid =Integer.parseInt(txt_id.getText());
            String upusername = txt_name.getText();
            String upaddress = txt_alamat.getText();
            //String upbirthdate = birthdate.setDateFormatString();
            String upbirthdate = String.valueOf(fm.format(birthdate.getDate()));
            String upnohp=txt_hp.getText();
            String upkelamin=txt_kelamin.getSelectedItem().toString();
            String upcekin = String.valueOf(fm.format(checkin.getDate()));
            String upcekout = String.valueOf(fm.format(checkout.getDate()));
            String uptykamar=txt_tykamar.getSelectedItem().toString();
            String upkamar=txt_nokamar.getSelectedItem().toString();
            String upprice=txt_harga.getText();

            String result = dbi.Update(upid, upusername, upaddress, upbirthdate, upnohp, upkelamin, upcekin, upcekout, uptykamar, upkamar, upprice);
            DefaultTableModel defTable = (DefaultTableModel) tabeldata.getModel();
            defTable.setRowCount(0);
            //Menampilkan data hasil inputan
            tampilancostumer();
            //Menampilkan feedback dari server
            JOptionPane.showMessageDialog(null, result,"Sukses",JOptionPane.INFORMATION_MESSAGE);
            //Menghapus inputan
            clearInput();
            //Menampilkan error saaat mengupdate data
        } catch (NumberFormatException | NotBoundException | MalformedURLException | RemoteException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex,"ERROR",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datacostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datacostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datacostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datacostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datacostumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Delete;
    public javax.swing.JButton Insert;
    public javax.swing.JButton Kembali;
    public javax.swing.JButton Reset;
    public javax.swing.JLabel address;
    public javax.swing.JLabel cekin;
    public javax.swing.JLabel cekout;
    public javax.swing.JLabel idk;
    public javax.swing.JLabel idk1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jkelamin;
    public javax.swing.JLabel kamar;
    public javax.swing.JLabel nohp;
    public javax.swing.JLabel price;
    public javax.swing.JLabel price1;
    public javax.swing.JTable tabeldata;
    public javax.swing.JLabel tlahir;
    public javax.swing.JTextField txt_alamat;
    public com.toedter.calendar.JDateChooser txt_birthdate;
    public com.toedter.calendar.JDateChooser txt_checkin;
    public com.toedter.calendar.JDateChooser txt_checkout;
    public javax.swing.JTextField txt_harga;
    public javax.swing.JTextField txt_hp;
    public javax.swing.JTextField txt_id;
    public javax.swing.JComboBox txt_kelamin;
    public javax.swing.JTextField txt_name;
    public javax.swing.JComboBox txt_nokamar;
    public javax.swing.JComboBox txt_tykamar;
    public javax.swing.JLabel typekamar;
    public javax.swing.JButton update;
    public javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
